# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KozuXmlIntegrator
                                 A QGIS plugin
 法務局地図XML（公図）を地形情報と照合し、森林境界確認用の実用的な地図データへ統合・調整するためのQGISプラグインです。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-15
        copyright            : (C) 2026 by Hideharu Masai
        email                : hideharumasai@void.mints.ne.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load KozuXmlIntegrator class from file KozuXmlIntegrator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .kozu_xml_integrator import KozuXmlIntegrator
    return KozuXmlIntegrator(iface)
